name = "rss-description-generator"
compatibility_date = "2024-08-13"
pages_build_output_dir = "./dist"

# [vars]
# MY_VAR = "my-variable"

[[kv_namespaces]]
binding = "KV"
preview_id = "5b329ead3afd406f97afa3d67cf0653c"

# [[r2_buckets]]
# binding = "MY_BUCKET"
# bucket_name = "my-bucket"

# [[d1_databases]]
# binding = "DB"
# database_name = "my-database"
# database_id = ""

# [ai]
# binding = "AI"